###配置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka
#hystrix的超时时间---服务端
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 8000
#ribbon的超时时间---客户端
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000